apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: argocd
spec:
  selector:
    matchLabels:
      app: argocd
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
        - name: argocd
          image: shekarsoma493/ekart:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster
