apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ekart:${BUILD_NUMBER}
spec:
  selector:
    matchLabels:
      app: ekart:${BUILD_NUMBER}
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ekart:${BUILD_NUMBER}
    spec:
      containers:
        - name: ekart:${BUILD_NUMBER}
          image: shekarsoma493/ekart:${BUILD_NUMBER}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster
