apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ekartargo
spec:
  selector:
    matchLabels:
      app: ekartargo
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ekartargo
    spec:
      containers:
        - name: ekartargo
          image: shekarsoma493/ekart:12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster
